### ISSUE TITLE
button PlayNow in context menu of track doesn't have implementation

### ISSUE THREAD

**Issue by G-Milevski** [nukeop/nuclear#403] opened 2019-07-12 23:45 UTC
Hello.
When i am investigating project I found that button playNow has action playSong but the action doesn't have implementation. In console is had an error "Uncaught TypeError: actions.playSong is not a function".

I can try to fixed this issue.

I'm sorry if this issue is duplicate. I newbie in opensource comunity. It's project my first try =)

**Comment by olafur-palsson** [comment] 2019-07-13 01:07
I think this could be caused by the doubleclick thing that was added today. The problem should be related to 'TrackRow' and 'TrackPopupContainer'.

**Comment by G-Milevski** [comment] 2019-07-13 07:13
@olafur-palsson Thanks for your fast answer and fixing.

**Comment by nukeop** [comment] 2019-07-15 19:50
Fixed by that pull request.

**Closed** 2019-07-15 19:50 UTC
