### ISSUE TITLE
Missing library when installing RPM package

### ISSUE THREAD

**Issue by Masgalor** [nukeop/nuclear#949] opened 2021-05-21 13:38 UTC
**Platform:**
OpenSuSe Tumbleweed

**Nuclear version:**
v0.6.13

**Description of the issue:**
The RPM package requires the library `libuuid` but in tumbleweed it is called `libuuid1` so the package can not be installed.
I propose to require `either libuuid OR libuuid1` unfortunately I do not understand how the packaging with github workflows works so I can not open a PR to fix this.

**Comment by nukeop** [comment] 2021-05-21 13:47
Building is done through electron builder and configured here: https://github.com/nukeop/nuclear/blob/master/package.json#L160

Needs to be investigated if we can fix this by using any of these options.

**Comment by Masgalor** [comment] 2021-05-21 13:49
Thanks for the hint, I will have a look.

**Comment by Masgalor** [comment] 2021-05-21 16:34
Additional information:
The package can be installed ignoring the dependency-error if the binary `libuuid.so.1` is present in a common lib path (e.g. `/usr/lib64/`).
There is no icon installed/associated with the application.

**Comment by nukeop** [comment] 2021-05-21 16:56
Broken icon is a known issue, it's caused by electron-builder on Linux distros. 

Tumbleweed is rolling right? I'll see what I can do about these dependencies for the next release. Until I figure it out, appimage should work (I know it's not ideal).

**Comment by Masgalor** [comment] 2021-05-21 17:12
Thank you for your time, this issue is definitely not a important one.

The appimage works fine and the rpm can be installed as well if you ignore the dependency error.
`libuuid1` is a base library and always installed, I only reported this because most users would not feel comfortable ignoring a dependency error.

You are right Tumbleweed is rolling, but there is no `libuuid` in Leap (non-rolling) either.

Could the icon problem be solved by adding it manually to the desktop-entry, something like this:
```
"desktop": {
    "Name": "Nuclear",
    "Name[es]": "Reproductor de música Nuclear",
     "Comment[es]": "Reproductor que retransmite música desde fuentes encontradas automáticamente."
     "Icon": "/opt/nuclear/resources/media/512x512.png"
},
```

**Comment by nukeop** [comment] 2021-05-21 23:14
I don't think it's getting packaged with the program. I'll check again if the issue has been fixed in the new electron builder.

**Closed** 2024-08-06 23:41 UTC
Labels: bug
