### ISSUE TITLE
Wrong JSON format sometimes causing window & player to break

### ISSUE THREAD

**Issue by DrachenfeuerHD** [nukeop/nuclear#1328] opened 2022-10-05 22:12 UTC
**Platform:** Linux x64

**Nuclear version:** 9545bf

**Description of the issue:** Sometimes if i add a song to a playlist the json gets formatted wrong. If i then try to play this song nuclear gets "blank" and nothing works until i restart. Here is an example of what i mean:

A right & working formatted json entry of a playlist:

![image](https://user-images.githubusercontent.com/35228631/194172955-1f8e0e82-3f13-42d5-a59f-6940542b5b47.png)

And sometimes it gets messed up and ends up looking like this:

![image](https://user-images.githubusercontent.com/35228631/194172994-99b583e4-d2a5-4d55-a76b-10ab25991080.png)

There the "artist" is not in one line causing the program to break. Even if i remove it from the playlist and add it again this specific song gets messed up. 

Here is an example song to reproduce this issue:  Firestone (feat. Conrad Sewell)

If i now create a new playlist and add any song & and then add Firestone (feat. Conrad Sewell) and hit play my player turns blank. Sometimes it will start but if i skip the song (to the "broken" one) it will crash.

It is possible to fix this issue by manually exporting the playlist, editing the wrong lines (to match the correct ones) and reimport it. 

But if i add a broken song again it will break.

**Comment by nukeop** [comment] 2022-10-05 22:21
I've seen this reported a couple of times recently on discord, the solution was just as you described. Not sure what causes it, but there must be a piece of code that saves artists wrong.

**Comment by tauantcamargo** [comment] 2022-10-07 16:56
@nukeop could i get this issue?

**Comment by nukeop** [comment] 2022-10-07 18:53
Sure, just let me know where the issue is when you locate it.

**Comment by tauantcamargo** [comment] 2022-10-07 18:57
@nukeop ok

**Comment by nukeop** [comment] 2022-10-16 19:18
Fixed with https://github.com/nukeop/nuclear/commit/d635500049a89fd77b59f2f6e8e3de64694040ec

**Closed by nukeop** 2022-10-16 19:18 UTC
Labels: bug
