### ISSUE TITLE
config.json settings preventing app from loading

### ISSUE THREAD

**Issue by jenyeeiam** [nukeop/nuclear#453] opened 2019-08-16 00:06 UTC
Just pulled from master, and my local app is giving me this error. Anyone else getting this?
<img width="517" alt="Screen Shot 2019-08-15 at 5 03 58 PM" src="https://user-images.githubusercontent.com/19957645/63134581-ee852b00-bf7e-11e9-834e-65bf7acabc9f.png">

**Comment by nukeop** [comment] 2019-08-16 00:11
I don't think so, I just did the same and don't see any such errors.
Your config might be broken, this is related to loading custom equalizer settings.

**Comment by jenyeeiam** [comment] 2019-08-16 00:15
Oh? I don't even know how that happens :(. What are the default settings?

**Comment by nukeop** [comment] 2019-08-16 00:17
The config is stored in `~/.config/nuclear/config.json`. If you delete it, it should be regenerated. Maybe it'll be worth it to check if it loads correctly and regenerate it from scratch if it isn't.

**Comment by jenyeeiam** [comment] 2019-08-16 00:25
I don't have the directory ~/.config/nuclear/
Could it be somewhere else?

**Comment by nukeop** [comment] 2019-08-16 00:28
https://electronjs.org/docs/api/app#appgetpathname

This is how the path is generated depending on platform.

**Comment by nukeop** [comment] 2019-08-16 00:32
I have to go to sleep now but if you still get this I'll help you some more tomorrow.
Please also change the title of the issue to something more descriptive (up to you), because this problem will need to get addressed in a better way, e.g. by checking if the config is valid on startup.

**Comment by jenyeeiam** [comment] 2019-08-16 00:34
Sure. Thanks for the the help so far :)

**Comment by jenyeeiam** [comment] 2019-08-16 01:38
I found the config.json file. The path is actually logged to the terminal as listed in store.js. I deleted the file and it was regenerated but still no luck.

Here's my config.json
{
	"lastFm": {},
	"settings": {},
	"localMeta": {},
	"localFolders": [],
	"playLists": [],
	"favorites": {
		"tracks": [],
		"artists": [],
		"albums": []
	},
	"equalizer": {
		"selected": "Default"
	}
}
<img width="555" alt="Screen Shot 2019-08-15 at 6 37 43 PM" src="https://user-images.githubusercontent.com/19957645/63137629-e1bb0400-bf8b-11e9-8490-b8c002b25009.png">

**Comment by nukeop** [comment] 2019-08-16 07:38
I think it might be the other way around, the config is not initialized correctly. I'll fix this later today.

**Comment by nukeop** [comment] 2019-08-17 00:43
Ok I was able to reproduce this. Now trying to fix it.

**Comment by nukeop** [comment] 2019-08-17 00:43
Btw, the config is actually in `~/.config/Electron/config.json`.

**Closed** 2019-08-17 00:47 UTC

**Comment by jenyeeiam** [comment] 2019-08-17 00:53
Up and running again!  Thanks @nukeop!
