### ISSUE TITLE
Nuclear Process keep open after close the App in Linux.

### ISSUE THREAD

**Issue by githubtefo** [nukeop/nuclear#668] opened 2020-03-08 19:58 UTC
![Screenshot_20200308_155816](https://user-images.githubusercontent.com/11220103/76170163-b2e9c280-6155-11ea-80c8-eb426a379658.png)

**Comment by nukeop** [comment] 2020-03-08 20:18
Did you install it from snap?

**Comment by githubtefo** [comment] 2020-03-08 22:23
Hi @nukeop, thanks for your reply.
No, I installed it from [](https://aur.archlinux.org/packages/nuclear-player-bin/)

**Comment by nukeop** [comment] 2020-03-09 18:24
I was able to reproduce this.
Seems that something gets left over if you close the windows using Alt+F4 (or whatever your window manager uses for closing programs), but if you click the X button, it closes correctly.

**Comment by githubtefo** [comment] 2020-03-11 02:12
In my case it also happens if I click the X button. BTK, I'm not using the CSD and under KDE plasma.

**Comment by nukeop** [comment] 2020-03-12 23:23
I also noticed that this prevents the program from launching later, since we check if the player is already running when launching.

**Comment by tghgg** [comment] 2020-04-13 08:18
I'm taking a look at this. Might be able to fix this with my mediocre Electron skills.

**Comment by nukeop** [comment] 2020-04-13 10:32
This is caused by this function: https://github.com/nukeop/nuclear/blob/master/packages/main/src/main.ts#L77

We commented app.close and forgot to uncomment it

**Comment by tghgg** [comment] 2020-04-14 05:20
If it's actually that simple then I've made a PR. Can't test the new build because I can't get `lerna` to work on my system for some reason, but it _probably_ works.

**Comment by nukeop** [comment] 2020-04-19 17:25
fixed by #689

**Closed by nukeop** 2020-04-19 17:25 UTC
Labels: bug, good first issue
