### ISSUE TITLE
MPEG-3 Support

### ISSUE THREAD

**Issue by yuckdevchan** [nukeop/nuclear#1269] opened 2022-04-24 22:07 UTC
I'm not a fan of MP3, but I need to use them for playing music on my phone, mp3 player and other stuff. At the moment I just convert them but I think that downloading in mp3 should be supported.

**Comment by nukeop** [comment] 2022-04-24 22:10
Duplicate of #1233

**Closed by nukeop** 2022-04-24 22:10 UTC
Labels: enhancement
