### ISSUE TITLE
SyntaxError: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by kohane27** [nukeop/nuclear#1308] opened 2022-08-18 06:03 UTC
Hello there. Hope you're doing well. Thank you for creating nuclear. It makes streaming yt music much easier!

**Platform:**

Linux 5.19.1-arch2-1

**Nuclear version:**

nuclear-player-bin 1656321745104:2022627_267b920591069c3daa0652269aa20cb9-2

**Description of the issue:**

To reproduce:

1. run `nuclear` in the terminal to see the error output
2. search "Coldplay"
3. click Tracks
4. double click any song
5. error produced

```
❯ nuclear
      main › (node:374419) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
  renderer › youtube track search error
  renderer › evalmachine.<anonymous>:11
"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)};Wka(ncode);
                                                                                                         ^

SyntaxError: Invalid regular expression: missing /
    at new Script (vm.js:101:7)
    at Object.t.decipherFormats (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:11501026)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async t.getInfo (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:11497843)
  renderer › Error while searching  for Lofi Girl lofi hip hop radio - beats to relax/study to on Youtube
  renderer › Error: Warning: topTrack.url is undefined, removing song
    at I (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:7076551)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async M.search (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:7053903)
    at async file:///opt/nuclear/resources/app.asar/dist/main.ea61db2c9233b43c043b.js:1:390362
```

Any input is much appreciated. Thank you:)

**Comment by AndreJesusBrito** [comment] 2022-08-18 20:45
This is happening to me as well...
Every song that I try to play gives this error, including in the top tracks
I used Nuclear yesterday and it was working fine
It works with local files so the problem is probably in the instance/server side

**Comment by nukeop** [comment] 2022-08-18 22:02
I can't reproduce this on Linux, and I don't have access to Windows - needs to be debugged by someone who does.

**Comment by nukeop** [comment] 2022-08-18 22:27
This is caused by this issue: https://github.com/fent/node-ytdl-core/issues/1110

When it gets fixed there I will update this library in Nuclear.

**Comment by xtrahigh** [comment] 2022-08-27 16:50
Just to keep in touch: the issue is fixed in version 4.11.1.

**Comment by nukeop** [comment] 2022-08-30 14:41
New release building now

**Comment by nukeop** [comment] 2022-08-30 20:06
Fixed in new release

**Closed by nukeop** 2022-08-30 20:06 UTC
Labels: bug

**Comment by georgio893479874** [comment] 2025-05-05 12:21
High
