### ISSUE TITLE
Crash on launch due to the GPU process not being usable

### ISSUE THREAD

**Issue by IvarWithoutBones** [nukeop/nuclear#1268] opened 2022-04-22 14:11 UTC
**Platform:** NixOS Linux

**Nuclear version:** Prelease [f5ec0d](https://github.com/nukeop/nuclear/releases/tag/f5ec0d), specifically the Appimage.

**Description of the issue:**
When attempting to launch Nuclear on NixOS I got the following error:
```console
[nix-shell:~/.cache/nixpkgs-review/pr-169347-1]$ ./results/nuclear/bin/nuclear
      main › (node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
[2:0421/193633.580170:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
```
I have found an issue elsewhere which describes the same problem, see https://github.com/LedgerHQ/ledger-live-desktop/issues/4253#issuecomment-926215043. There someone suggested adding the `--no-sandbox` flag, which did fix the issue for me. Maybe updating electron will properly fix it as described in said issue?

I maintain the nuclear package in [nixpkgs](https://github.com/NixOS/nixpkgs), there we will wrap the binary to always use the `--no-sandbox` flag by default in the meantime.

**Comment by JustANormalTinker** [comment] 2022-06-11 12:38
This also seems to occur on the .deb package.
`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[12346:0611/180514.265417:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
fish: Job 1, 'nuclear' terminated by signal SIGTRAP (Trace or breakpoint trap)
` 
But the driver name seems to be null somehow

**Comment by nukeop** [comment] 2022-09-12 18:02
Duplicate of #1297, can you try running with `--no-sandbox`? I was told (on Discord) that it helped in this case. Please reopen if it doesn't work.

**Closed by nukeop** 2022-09-12 18:02 UTC
Labels: bug
