### ISSUE TITLE
It keeps loading on Arch linux, no errors in terminal

### ISSUE THREAD

**Issue by wdub** [nukeop/nuclear#119] opened 2019-01-16 11:56 UTC
I've just installed nuclear-player 0.4.3-2 from AUR and it doesn't seem to work or start properly. I can see the loading animation and nothing else.
Does anyone know what is going on?

**Comment by fazo96** [comment] 2019-01-16 12:24
Looks related to https://github.com/nukeop/nuclear/issues/118

**Comment by nukeop** [comment] 2019-01-16 12:34
This can also be caused by lacking permissions to store the config file in /home, I addressed this after the release. Could possibly be solved in the development version.

**Comment by wdub** [comment] 2019-01-16 12:58
@fazo96 yep, it's the same behaviour.
@nukeop I can create them manually if someone will post a list with the config files.

**Comment by joaoantoniocardoso** [comment] 2019-01-21 13:00
Today I just installed 0.4.3-1 from AUR and it is loading and playing from both Youtube and Soundcloud Plugins.

**Comment by nukeop** [comment] 2019-01-21 13:12
New version will contain many bugfixes (thanks to the help from @trekiteasy , @CAnderson97 and others), and should get rid of this and other similar problems once and for all.

**Comment by nukeop** [comment] 2019-02-14 23:20
Pretty sure this is fixed now.

**Closed by nukeop** 2019-02-14 23:20 UTC
Labels: bug
