### ISSUE TITLE
Not playing

### ISSUE THREAD

**Issue by bagaweb** [nukeop/nuclear#1314] opened 2022-08-25 14:16 UTC
**Platform:**
Mint 21

**Nuclear version:**
nuclear-3f9007

**Description of the issue:**
The player is not playing. not working with streaming, neither with local files.

Tried both deb and appimage.

Icon is also missing from menu and panel.

**Comment by nukeop** [comment] 2022-08-25 15:54
Duplicate of #1308

There is a broken dependency that will need to be fixed before the player can work.

**Comment by bagaweb** [comment] 2022-08-25 15:56
Alright thanks!
Will this fix the missing icons as well?

**Comment by bagaweb** [comment] 2022-08-25 16:00
Thank you @nukeop

**Comment by mYnDstrEAm** [comment] 2022-08-30 11:27
Also having the icon issue. For the local files check if this is a duplicate of: #1008

**Closed** 2023-07-26 11:19 UTC
Labels: bug
