### ISSUE TITLE
Tracks in playlists don't play (youtube track search error)

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#1317] opened 2022-08-30 11:40 UTC
**Platform:** Debian 11/KDE

**Nuclear version:** latest (please add version numbers for pre-release versions!) ([3f9007](https://github.com/nukeop/nuclear/releases/tag/3f9007))

**Description of the issue:**
Worse than not playing local files (#1008), Nuclear now also can't play tracks from playlists anymore (the playlist does not contain any local files).

This is the output in the console when I try to play a track in a playlist (the track played previously and the same thing happens when I click on the PLAY button of the entire playlist rather than any individual track):

```
      main › Main process failed to react to IPC clear queue event
      main › error trying to set discord activity
  renderer › youtube track search error
  renderer › evalmachine.<anonymous>:13
"',};Xka(ncode);
^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:101:7)
    at Object.t.decipherFormats (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:11501026)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async t.getInfo (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:11497843)
  renderer › Error while searching  for {Track name} on Youtube
  renderer › Error: Warning: topTrack.url is undefined, removing song
    at I (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:7076551)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async M.search (file:///opt/nuclear/resources/app.asar/dist/726.73fd16dcf7d7e9583890.js:2098:7053903)
    at async file:///opt/nuclear/resources/app.asar/dist/main.ea61db2c9233b43c043b.js:1:390362
```
I replaced the track name by {Track name} above - it happens with all tracks.

**Comment by nukeop** [comment] 2022-08-30 11:52
Duplicate of #1308 (which I'm going to reopen)
I already fixed it on my local copy but some typechecks are not passing - fix should be available today

**Closed by nukeop** 2022-08-30 11:52 UTC
Labels: bug
