### ISSUE TITLE
Search bar support for song/playlist url

### ISSUE THREAD

**Issue by MannPE** [nukeop/nuclear#171] opened 2019-01-22 00:35 UTC
Would love to add support to the search functionality so we could type a playlist/song url from youtube and have the appropriate songs appear as a result. Would make adding our current music libraries way easier.

**Comment by nukeop** [comment] 2019-01-22 08:44
The problem is that there's no way to get artist/track name/album from a youtube URL, which would disable some functionalities (such as scrobbling). Youtube does not attach any metadata to the videos.

**Comment by trekiteasy** [comment] 2019-01-22 13:33
In fact, there are some turnarounds (thanks npm) :
youtube-playlist + get-artist-title + our lastfm track search could give us something 
I'm not too far from pushing something to get all tracks from a search on a youtube playlist url

**Comment by nukeop** [comment] 2019-01-22 13:42
That could be nice. There was a search feature for youtube playlists in the previous version (0.3.0), but it did not fit nicely with current search model, which treats metadata as a starting point (as in, the data Discogs provides).

**Comment by trekiteasy** [comment] 2019-01-23 08:33
I just committed something which allows to put a playlist url in the search bar (https://github.com/nukeop/nuclear/commit/5a24449c21ff6819d35e43ab5c98f205e75165c6) : as stated in the commit : 
Known limitations :
- we should also be able to enter a song url (and not only a playlist url) - not implemented
- for now, only the first 100 songs of the playlist are displayed
- some functionalities like "add all" or play all would make sense

**Comment by nukeop** [comment] 2019-01-23 08:58
I don't really like this, since this is in effect a hidden functionality (not obvious from UI and not discoverable). I think this could be solved better by:
*Adding a dropdown to the search box to select a search provider (general/metadata search and playlists - the former could be handled by Discogs like it works now, or in the future by combining Discogs and MusicBrainz)
* Adding validation for each search provider so that the users know how to use it, along with a placeholder demonstrating an example. This should color the search box or its border red if the input is invalid, and provide a tooltip/popover with more information.

**Comment by trekiteasy** [comment] 2019-01-23 09:55
I agree on the "hidden functionality" thing. 
But on a larger scale : I'm not sure how, but I feel the search / search results should be revamped. Maybe break it by search providers as you mentioned. Or maybe by type of results (are we searching for a track, an artist, a playlist ?), and put search sources as settings or plugins ? Even though I like the "omnibox component" where I can put anything and it gives me some results.
I am not clear at all on this (best articulation between search results types and search providers), so I don't feel like working on it yet myself.

**Comment by nukeop** [comment] 2019-01-23 10:06
I'd like to plan this work for later, since there's already plenty of features/adjustments I'd like to make before releasing 0.5.0, and even 0.6.0 is already chock full of stuff to do.

**Comment by Gnorme** [comment] 2019-02-13 17:21
If you try and use the search bar to search for a youtube playlist, no results are returned. 

Steps: Paste a youtube playlist link: ` https://www.youtube.com/playlist?list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG ` in to the nuclear search bar. Select the playlist tab. No search results are returned.

Expected behavior: A list of songs is displayed that matches those found in the youtube playlist ink.

The issue is with the youtube-playlist package which currently uses 'got' for its http request. I was able to get the expected behavior by replacing the 'got' package in youtube-playlist with request-promise.

**Comment by HaiDang666** [comment] 2021-05-28 04:42
this function is not working with `playlist link`, still works for `video link`

**Closed** 2021-06-15 07:55 UTC
Labels: feature request, good first issue
