### ISSUE TITLE
"Play next" feature puts a song on the bottom of queue and shifts current playing song

### ISSUE THREAD

**Issue by Saltane** [nukeop/nuclear#1420] opened 2023-03-11 13:00 UTC
**Platform: GNU/Linux**

**Nuclear version: nuclear-fd06a3.AppImage**

**Description of the issue:** having some queue already playing.
![image](https://user-images.githubusercontent.com/101461606/224485330-d82d6bb0-74a4-43e8-9c1e-bd7ce590c523.png)

Having local playlist opened, clicking playlist's song three-dot menu next to + button and selecting "Play next" option.
![image](https://user-images.githubusercontent.com/101461606/224485398-c3114325-6218-43af-8d71-9977ede81540.png)

Nuclear adds chosen song on the second-bottom place in queue and to make things worse, it starts playing one song back relatively to current playing one, so in this particular case it was Skillet playing and after new song was added via "Play next" feature it started playing Johny cash, which was one before Skillet.
![image](https://user-images.githubusercontent.com/101461606/224485425-7ec35ad4-2fd1-4922-8446-f3d698c6d14a.png)

**Expected:** "Play next" puts chosen song right after current playing one and lets current playing song continue playing.

**Comment by nukeop** [comment] 2023-03-11 18:22
I can confirm that this doesn't work as intended currently, needs to be tested and fixed. I'll try doing it soon.

**Comment by terryyLi** [comment] 2023-04-17 02:14
Hi my team would like to try fixing it. Could you assign it to me?

**Comment by nukeop** [comment] 2023-04-17 07:19
Sure. Here are our developmet resources: https://nukeop.gitbook.io/nuclear/developer-resources/development-process

**Comment by akakayan** [comment] 2023-04-19 02:28
Hi, I make some change and think I've fixed the issue. I've submitted the pull request. Do I need to be an assignee or if there is anything else I should do?

**Closed** 2023-04-23 20:45 UTC
Labels: bug, good first issue
