### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by AhamedBilal** [nukeop/nuclear#1079] opened 2021-10-19 07:01 UTC
**Platform:**
OS: Manjaro Linux x86_64 
Kernel: 5.13.19-2-MANJARO 
DE: Plasma 5.22.5 
Theme: OrchisDark [Plasma], Breeze [GTK2/3] 

**Nuclear version:**
0.6.16
**Description of the issue:**
![Screenshot_20211019_123106](https://user-images.githubusercontent.com/45702667/137859655-34b1cbf7-d9ac-46c7-92ac-f64a59806bf8.png)

**Comment by HaiDang666** [comment] 2021-10-21 01:41
Can you try v0.6.17, download fixed in https://github.com/nukeop/nuclear/commit/6a03063384c7aee39efdc201711291f421941c4f

**Comment by dasanchez981** [comment] 2021-11-13 02:14
OS: MacOs 11.6
Nuclear Version: 0.6.17

Hi, I could not replicate this issue; I am able to download songs correctly. Are there any more steps to reproduce?

**Comment by nukeop** [comment] 2021-11-13 22:39
Yep, I also can't reproduce this on Mac. Maybe you're getting geoblocked.

**Comment by AhamedBilal** [comment] 2021-11-14 04:34
Works in Windows 11.

**Comment by kbojanek** [comment] 2021-11-15 16:43
Specific album giving issues is colourgrade - tirzah. other albums seem to be working fine

**Comment by nukeop** [comment] 2021-12-01 00:25
I tried this album a couple of times, and every time I was able to download it with no problems. I'm going to close this since I can't reproduce this issue.

**Closed by nukeop** 2021-12-01 00:25 UTC
Labels: bug
