### ISSUE TITLE
Add current track to favorites

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#311] opened 2019-04-18 11:53 UTC
It would be nice to add the track I'm currently listening to favorites (or to a playlist) easily. Without searching for it + adding it from the search results. (Something like a"Star" button or a "add to playlist) in the control panel

**Comment by nukeop** [comment] 2019-04-22 20:02
I will add a button for favoriting to TrackRow. I've also added a context popup option for favoriting tracks earlier, but I suppose it should also be accessible more conveniently.

**Comment by nukeop** [comment] 2019-04-23 22:12
This is now implemented. I'm also thinking of adding two extra buttons in the bottom left corner, between the cover art and track title/artist, one for favoriting and one for playlist management functions.

**Comment by SelfDevTV** [comment] 2019-06-26 20:00
Hi @nukeop 
I have a lot of spare time and also want to give this one a try. The other issue I'm currently working on I have to wait for the OP to respond since it's not reproducable on my site. 

So to this request:

* A star button for adding the currently played song to favorites (between the little album cover bottom left and the title + interpret right?) I think I'm able to implement this.

**Comment by nukeop** [comment] 2019-06-26 20:43
For now try focusing on the favorite (star) button to get a feel of the workflow. Once you add that and see what the review/merge process looks like, you'll be in a better position to add something more complex, like the playlist management menu. This button should be placed somewhere in the bottom bar, to make it clear that it's connected to the currently playing track, and should be disabled when there's nothing in the queue. Up to you where to place it exactly.

I would like to avoid showing a popup upon clicking anywhere, because it's bad practice from the UX point of view - there's no way to predict that it will happen from the look of the UI elements, it breaks user expectations (we want interactive elements to be clearly distinguished from the rest of the interface), and it creates difficult situations (e.g. what happens when you click a button that's also in the bottom bar? what takes precedence?)

Your option 2 sounds sensible and you should be able to find examples of similar patterns throughout the code. Try running the dev version of locally and poke at the code to see what does what.

Branch naming is up to you, it matters mainly for the repository maintainers since we share the same fork. When you fork the repository it belongs to you, and you're the one deciding how to name the branches from that point on. When you start a pull request the branch gets merged into master anyway. Personally, most often I'm using names like `feature/feature-name`, `bug/bug-name`, and `hotfix/hotfix-name`.

**Comment by SelfDevTV** [comment] 2019-06-26 20:49
Thank you very much :) 
I'm already running it on my machine and it works perfectly fine. 

I will start to add the favorite button right now and get comfortable with the whole process.

Also good point with the UX I aggree with you. It's not obvious that it can be clicked and does something. So rather show a clean visible star button. 

Cheers,
Geralt

**Comment by nukeop** [comment] 2019-06-26 21:09
Great, and if you want any help or comments, feel free to open a pull request with your changes, even if you're not done with the feature. It's perfectly fine to open a "work in progress" pull request if you're stuck or just want to make sure you're doing everything correctly. I'm not sure how much experience you have with React or Github in general, so pardon me if I'm explaining something obvious, I just want to make sure we're on the same page even if I end up talking about something that goes without saying.

**Comment by SelfDevTV** [comment] 2019-06-26 22:17
@nukeop Yeah sure thanks for the heads up.
Two questions:

* Is there any way to get the currently played song? I just found `queue.currentSong` but that is just a number. Any way to identify a song?
* Is there any identification on the song objects. I can't find any when I log it with console.log. I ask because I want to button to be fully opacity when the song currently played is already his favorite. I mean I can get the users current songs and try to match the current song title with the titles in his fav songs array, but wouldn't it be easier to add an id to them? Or is it impossible because of the several sites it's fetching the songs (e.g.  youtube, soundcloud etc.)? 

So far looking good. Button is implemented and working. But now I want to show the button with full opacity when song is already a fav and user can unfav it with click :)

**Comment by SelfDevTV** [comment] 2019-06-26 22:17
> @nukeop Yeah sure thanks for the heads up.
> Two questions:
> 
> * Is there any way to get the currently played song? I just found `queue.currentSong` but that is just a number. Any way to identify a song?
> * Is there any identification on the song objects. I can't find any when I log it with console.log. I ask because I want to button to be fully opacity when the song currently played is already his favorite. I mean I can get the users current favorite songs and try to match the current song title with the titles in his fav songs array, but wouldn't it be easier to add an id to them? Or is it impossible because of the several sites it's fetching the songs (e.g.  youtube, soundcloud etc.)?
> 
> So far looking good. Button is implemented and working. But now I want to show the button with full opacity when song is already a fav and user can unfav it with click :)

**Comment by nukeop** [comment] 2019-06-26 22:54
Queue also has a `queueItems` key which stores a list of everything in the queue. The `currentSong` key stores the index into that list corresponding to the currently playing track.

Your guess is correct that it's technically impossible to match songs due to the numerous sources, but typically we'd just compare the artist/track pair and for some purposes it's enough. You don't need to reinvent the wheel here though, just do it the same way it's done when adding from the queue menu:

https://github.com/nukeop/nuclear/blob/master/app/components/PlayQueue/QueueMenu/QueueMenuMore/index.js

The `addFavoriteTrackFromQueue` function handles adding the current track as a favorite, you can look at this component to see how it's used and you just need to do something similar. Perhaps you could extract that function to some other file so you can reuse it, copy&paste should be avoided.

Btw, you can use an icon of an empty star if the song isn't added yet, and a filled star if it is. I think this will be consistent with what users generally come to expect.

**Comment by olafur-palsson** [comment] 2019-06-30 02:08
Footer is implemented in App.js and App.js has the queue and currently playing track in props. Can be done like this https://github.com/nukeop/nuclear/compare/master...olafur-palsson:current2favorite

**Comment by kvsm** [comment] 2019-10-12 23:36
Is this still being worked on? I would pick it up if not.

**Comment by nukeop** [comment] 2019-10-13 23:15
I don't think there are any pull requests open, so you can take this. Let me know if you need any help.

**Comment by HaiDang666** [comment] 2021-06-28 02:18
Implemented

**Closed by HaiDang666** 2021-06-28 02:18 UTC
Labels: enhancement, feature request, good first issue
