### ISSUE TITLE
Javascript error (flatpak 0.6.17)

### ISSUE THREAD

**Issue by jonfive** [nukeop/nuclear#1197] opened 2022-02-07 01:01 UTC
**Platform:**
flatpak
**Nuclear version:**
0.6.17
**Description of the issue:**
error in main - Images are in order of receipt.
![image](https://user-images.githubusercontent.com/24421525/152709688-ff2de737-f1f7-4787-89e3-82b9e6549892.png)
![image](https://user-images.githubusercontent.com/24421525/152709710-2cf6ed42-67b2-44fd-b0c7-952f8ea2220b.png)
![image](https://user-images.githubusercontent.com/24421525/152709725-ca9854cc-d157-440f-ba7b-5d146d30443b.png)

**Comment by nukeop** [comment] 2022-02-07 01:03
Duplicate of #1081

**Closed by nukeop** 2022-02-07 01:03 UTC
Labels: bug
