### ISSUE TITLE
Blank app when opening

### ISSUE THREAD

**Issue by rbvto** [nukeop/nuclear#79] opened 2018-07-12 12:51 UTC
Mac information in annex, issue screenshot in annex
![screen shot 2018-07-12 at 9 43 00 am](https://user-images.githubusercontent.com/7452510/42633833-01d51802-85b8-11e8-92ef-5340d438c703.png)
![screen shot 2018-07-12 at 9 40 54 am](https://user-images.githubusercontent.com/7452510/42633874-15560dbe-85b8-11e8-8119-9993c894449d.png)

I've installed the app's latest beta release by using the .dmg package.
Copied the .app executable over to applications;
Navigated to the applications folder; and 
Right-clicked open to add a security exception (per apple instructions on how to run stuff from unidentified developers) but unfortunately the app seems to be blank!

This is the first time i've installed the app and i have only tried to install it by .dmg

I'll try other installation methods later (as i am currently in the middle of work) and will report back!

**Comment by nukeop** [comment] 2018-07-12 13:00
I'll add something to save logs to a file so we can take a closer look at the problem... I'm cross-compiling for Mac OS as I don't have access to a Mac, but I remember it worked some time ago. Might be another update to youtube-dl.

**Comment by rbvto** [comment] 2018-07-12 13:12
Okay! Sounds good.

When you get the logs up and running let me know and i'll compile the repo and upload the logs

**Comment by nukeop** [comment] 2018-07-19 07:50
Yeah I know there's another issue in production. I've been trying to solve that for a while. The problem is that webpack doesn't bundle mpris dependencies in production and when the program tries to use them, it crashes. Now that I've fixed some other stuff, I'll try taking care of that (after I get back home from work).

**Comment by nukeop** [comment] 2018-08-05 20:47
I've changed a lot of stuff today, production build should work now.

**Comment by rbvto** [comment] 2018-08-06 11:54
Okay! I'll try to compile and report in a bit.

**Comment by rbvto** [comment] 2018-08-06 12:33
@nukeop I was able to compile and run everything as expected!

Node: 10.8.0
Npm: 6.3.0

In my opinion this issue can be closed, what do you think?

<img width="1426" alt="screen shot 2018-08-06 at 9 31 45 am" src="https://user-images.githubusercontent.com/7452510/43716806-d32ca558-995b-11e8-8821-5eabbe210edd.png">

**Comment by nukeop** [comment] 2018-08-06 12:38
Great news, thanks for testing. I will close it now, if you have any problems in the future, please open a new issue.

**Closed by nukeop** 2018-08-06 12:38 UTC
