### ISSUE TITLE
Can not start on macOS Catalina ……

### ISSUE THREAD

**Issue by Antediluvian** [nukeop/nuclear#611] opened 2020-01-18 03:17 UTC
<img width="454" alt="CleanShot 2020-01-18 at 11 15 11@2x" src="https://user-images.githubusercontent.com/9662/72657813-11ab7f00-39e4-11ea-9ab0-aa39e588d3c6.png">

**Comment by nukeop** [comment] 2020-01-18 03:38
Thanks for opening this! I'll track this down asap and rebuild. Is this pkg, dmg,or both?

**Comment by trekiteasy** [comment] 2020-01-18 07:55
Same here with the dmg.

**Comment by kobespecial** [comment] 2020-01-18 15:18
Same here with the dmg

**Comment by nukeop** [comment] 2020-01-19 19:02
https://github.com/nukeop/nuclear/releases/tag/v0.6.1

Try this release

**Comment by lcerf** [comment] 2020-01-27 03:12
The latest release does not apparently solves the issue on Trisquel 8 (based on Ubuntu 16.04):
`$ nuclear 
      main › something fail during app bootstrap
      main › TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/opt/nuclear/resources/app.asar/dist/main.js:1929:111692)
    at t (/opt/nuclear/resources/app.asar/dist/main.js:1929:110842)
    at Object../node_modules/abstract-socket/lib/abstract_socket.js (/opt/nuclear/resources/app.asar/dist/main.js:1923:99362)
    at n (/opt/nuclear/resources/app.asar/dist/main.js:1:211)
    at /opt/nuclear/resources/app.asar/dist/main.js:1983:16185
    at e.exports (/opt/nuclear/resources/app.asar/dist/main.js:1983:16755)
    at c (/opt/nuclear/resources/app.asar/dist/main.js:1983:5395)
    at Object.e.exports.sessionBus (/opt/nuclear/resources/app.asar/dist/main.js:1983:5597)
    at $t.p.init (/opt/nuclear/resources/app.asar/dist/main.js:2185:46373)
    at new p (/opt/nuclear/resources/app.asar/dist/main.js:2185:46190)`

**Comment by nukeop** [comment] 2020-01-27 08:57
Does Trisquel come with dbus/mpris? Might be caused by this.

**Comment by lcerf** [comment] 2020-01-27 13:15
The D-Bus daemon is running but none of the packages apparently relating to mpris (mpris-remote, mopidy-mpris, pidgin-mpris, or mpdris2) is installed on my system.  Should one of them (which one?) be installed?

**Comment by nukeop** [comment] 2020-01-27 15:01
Rhythmbox shouldn't influence this. I'll try on a Trisquel VM.

How did you install Nuclear, btw?

**Comment by lcerf** [comment] 2020-01-27 15:12
I used GDebi to install https://github.com/nukeop/nuclear/releases/download/v0.6.1/nuclear-6fa42c.deb

**Comment by lcerf** [comment] 2020-02-02 16:26
Could you reproduce the error?

**Comment by nukeop** [comment] 2020-02-05 22:48
User pony on Discord told me that he was able to run on Deepin now, could you check please?

**Comment by lcerf** [comment] 2020-02-06 11:33
Sure.  I used GDebi to install https://github.com/nukeop/nuclear/releases/download/v0.6.3/nuclear-fca030.deb and the same error is now raised two lines later:
`$ nuclear 
      main › something fail during app bootstrap
      main › TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/opt/nuclear/resources/app.asar/dist/main.js:1931:112553)
    at t (/opt/nuclear/resources/app.asar/dist/main.js:1931:111703)
    at Object../node_modules/abstract-socket/lib/abstract_socket.js (/opt/nuclear/resources/app.asar/dist/main.js:1925:99612)
    at n (/opt/nuclear/resources/app.asar/dist/main.js:1:211)
    at /opt/nuclear/resources/app.asar/dist/main.js:1985:16185
    at e.exports (/opt/nuclear/resources/app.asar/dist/main.js:1985:16778)
    at c (/opt/nuclear/resources/app.asar/dist/main.js:1985:5395)
    at Object.e.exports.sessionBus (/opt/nuclear/resources/app.asar/dist/main.js:1985:5597)
    at lt.p.init (/opt/nuclear/resources/app.asar/dist/main.js:2187:46373)
    at new p (/opt/nuclear/resources/app.asar/dist/main.js:2187:46190)`

I tried to remove ~/.config/nuclear.  In vain.

**Comment by nukeop** [comment] 2020-02-06 21:05
Hm, are you able to install from snapcraft?

**Comment by lcerf** [comment] 2020-02-08 17:09
Trisquel does not package snapd & co., because the store is centralized and full of proprietary software (Snap's server-side is proprietary too, by the way).

I tried executing https://github.com/nukeop/nuclear/releases/download/v0.6.3/nuclear-fca030.AppImage and it failed as well:
`$ ./nuclear-fca030.AppImage 
      main › something fail during app bootstrap
      main › TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1931:112553)
    at t (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1931:111703)
    at Object../node_modules/abstract-socket/lib/abstract_socket.js (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1925:99612)
    at n (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1:211)
    at /tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1985:16185
    at e.exports (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1985:16778)
    at c (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1985:5395)
    at Object.e.exports.sessionBus (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:1985:5597)
    at lt.p.init (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:2187:46373)
    at new p (/tmp/.mount_nucleaiDHmD9/resources/app.asar/dist/main.js:2187:46190)`

**Comment by nukeop** [comment] 2020-02-08 18:48
This makes me think that we should ship it with source maps to make debug logs more useful. I will try to run the dev version on my Trisquel VM later to get to the bottom of it.

I think this is because of some dependency that should be optional but we unintentionally made it mandatory.

**Comment by nukeop** [comment] 2020-02-08 19:38
OK, I was able to finally reproduce this. Fix coming soon.

**Comment by nukeop** [comment] 2020-02-08 20:02
![ArchLabs-24-815x256](https://user-images.githubusercontent.com/12746779/74091291-b97d0f80-4aad-11ea-9efe-c0b84b6284d4.png)

@charjac if you have the time, could you please help me with debugging this? I also opened an issue on `dbus-next`: https://github.com/dbusjs/node-dbus-next/issues/49

This is related to initialization of the LinuxMediaService module, and could probably be fixed by catching an exception somewhere.

**Comment by charjac** [comment] 2020-02-09 11:29
@nukeop Sure, I take a look at this this evening.

**Comment by charjac** [comment] 2020-02-09 11:39
We could imagine a linux build without mpris support and handle it at webpack level.

**Closed** 2021-01-19 08:47 UTC
Labels: bug
