### ISSUE TITLE
Deleting tracks from queue issue

### ISSUE THREAD

**Issue by perspolis001** [nukeop/nuclear#340] opened 2019-06-04 19:51 UTC
I searched for specific songs and added them to the queue. This function worked well and didn't realize any bugs. But then I decided to check the delete from queue functionality. Deleting one song from the queue worked and the song disappeared. Same for the second time but after those when I tried to delete the remaining songs the system crashed and went back to the loading page when I first opened the software and never got out of that page unless I close it.

**Comment by nukeop** [comment] 2019-06-04 20:12
What version are you using?

**Comment by perspolis001** [comment] 2019-06-04 20:14
0.4.5

**Comment by nukeop** [comment] 2019-06-04 20:18
Thanks for reporting, I'll look into it.

**Comment by ngrant123** [comment] 2019-06-14 04:54
Can I check out this one? Trying to contribute to an open source project

**Comment by nukeop** [comment] 2019-06-14 07:42
I would be very grateful, especially if you can help with reproducing and finding the cause of this issue. If you manage to fix it on top of that, even better.

**Comment by ngrant123** [comment] 2019-06-26 13:50
My bad I just started a new job and stuff so be focusing on that if anybody wants to pick up this issue while im bullshitting go ahead lol i'm gonna eventually work on it

**Comment by nukeop** [comment] 2019-06-26 16:15
No problem, thanks for the update!

**Comment by SelfDevTV** [comment] 2019-06-26 19:27
Hi @nukeop I'm a self thaught dev and wanted to ask you if I can try this issue? 
I will be first working through the code base and then try to reproduce the error and find the bug.
In the last step I try to fix it. 
If I have green light I will start right now. 
Cheers Geralt

**Comment by nukeop** [comment] 2019-06-26 19:38
Yes, absolutely. If you can't reproduce this let me know too.

**Comment by SelfDevTV** [comment] 2019-06-26 19:46
@perspolis001 I could not reproduce the problem. Wasn't crashing on my site. 
Could you please explain the problem - step by step. 
Did you deleted it in a specific order and how exactly. Please as detailled as possible. 
Thank you very much. 
Geralt

**Comment by indreshattri** [comment] 2019-10-28 06:29
Hi @nukeop,
Can you please help me in reproducing in it. I was trying to give it a go but I couldn't reproduce it in the newest version.

Thank you very much
Indresh

**Comment by nukeop** [comment] 2019-10-29 20:44
Maybe it's been fixed? If neither of us can reproduce this, I'll close this. Worst case we can reopen this later.

**Closed** 2019-10-29 20:46 UTC
Labels: bug, good first issue
