### ISSUE TITLE
Unable to seek in certain tracks

### ISSUE THREAD

**Issue by mascherone108** [nukeop/nuclear#637] opened 2020-01-26 21:58 UTC
I can so far only reproduce it with this one track but I assume there are more like this: 

1. Search for Michael McCann
2. Click on his profile (the one with black and white picture)
3. Navigate to the Deus Ex Mankind Divided album
4. Play the "Prague" track
5. Try to seek/fast-forward/generally click on the track progression bar

**Comment by nukeop** [comment] 2020-01-26 22:08
I can't reproduce this bug on Linux. What platform are you running this on?

**Comment by KetchupEnthusiast** [comment] 2020-01-28 13:40
Windows
I just happened to do a clean reinstall and decided to try Nuclear on it and still the same. Before, I assumed that it could've been some misconfiguration/corrupted data or something, but it apparently wasn't.

**Comment by nukeop** [comment] 2021-06-15 08:01
Fixed now

**Closed by nukeop** 2021-06-15 08:01 UTC
Labels: bug
