### ISSUE TITLE
Getting "A Javascript error occurred in the main process" errors when playing tracks

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#1128] opened 2021-12-27 13:11 UTC
**Platform:** GNU/Linux/Debian11/KDE

**Nuclear version:** 0.6.17

**Description of the issue:**
See https://github.com/nukeop/nuclear/discussions/1075#discussioncomment-1486208
I get the same error as well as this one:
![screensh](https://user-images.githubusercontent.com/10249049/147474413-84f6519e-c767-4cf3-a7fc-2e609849f1a9.png)

This error message-box is shown when playing a stream file and when adding a file to the queue (the error of the screenshot above occurs after the latter). When playing a file often 3 or more errors are shown, including the error in the screenshot at the link and slightly different ones.
The errors also occur when nothing new is in the console output. The tracks usually play nevertheless. Couldn't find a bug report about it.

**Comment by BobIsMyManager** [comment] 2021-12-27 19:15
duplicate of  #1081

**Closed** 2021-12-27 22:25 UTC
Labels: bug
