### ISSUE TITLE
Play Now doesn't actually play the song until toggling play button

### ISSUE THREAD

**Issue by anoadragon453** [nukeop/nuclear#225] opened 2019-01-30 13:43 UTC
Playing a song via clicking it and hitting 'Play now' in the popup doesn't actually produce music until the play button is switched to pause, and then back to play.

* Search for a song
* Find one and click on it, then click "Play now" in the popup
* See the song go into the song queue, load, but not play
* Click play button twice.
* Song plays

**Comment by nukeop** [comment] 2019-01-30 14:07
Duplicate of #195 , thanks for reporting anyway,

**Closed** 2019-01-30 14:07 UTC
Labels: bug, duplicate
