### ISSUE TITLE
Songs do not play

### ISSUE THREAD

**Issue by plagasul** [nukeop/nuclear#801] opened 2020-12-29 14:53 UTC
I know there is a troubleshoot item and at least another issue, but this seemed different.

Everything seems to work except playing songs which remain at 00:00 without sound, and of course downloads.

The following is the output of starting nuclear 0.66 from CLI , switching to BEST SONGS tab, and trying to play Mariah Carey - All I want for christmas is you song, failing, and closing the app.

Nuclear is installed using app manager on Linux Mint 19.3 Cinnamon

```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No existe el fichero o el directorio
libGL error: failed to load driver: i965
      main › (node:3) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
      main › (node:3) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([ 'org.freedesktop.DBus.Error.ServiceUnknown' ])
    at er.emit (events.js:299:17)
    at n (/app/main/resources/app.asar/dist/main.js:2717:44875)
    at /app/main/resources/app.asar/dist/main.js:2717:45132
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
      main › (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      main › renderer › Error while searching  for Mariah Carey All I Want for Christmas Is You on Youtube
      main › renderer › Error: Error parsing info: Unexpected token ) in JSON at position 0
    at t.getBasicInfo (file:///app/main/resources/app.asar/dist/1.renderer.js:2240:278393)
    at async Map.getOrSet (file:///app/main/resources/app.asar/dist/1.renderer.js:2240:262532)
    at async t.getInfo (file:///app/main/resources/app.asar/dist/1.renderer.js:2240:280578)
    at async Map.getOrSet (file:///app/main/resources/app.asar/dist/1.renderer.js:2240:262532)
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
```

**Comment by PinkDev1** [comment] 2020-12-31 23:07
Issue also happening on Windows release. (v0.6.6).
Installed via setup exe from releases.

**Comment by Zealest** [comment] 2021-01-01 17:51
having the same issue on Windows 20H2 (19042.685)
installed via the [Setup.exe](https://github.com/nukeop/nuclear/releases/download/v0.6.6/nuclear.Setup.v0.6.6.exe)

**Comment by foss-** [comment] 2021-01-05 00:46
Dupe of https://github.com/nukeop/nuclear/issues/794 please close.

**Closed** 2021-01-05 01:03 UTC
Labels: bug
