### ISSUE TITLE
deleting a single item within a playlist which has duplicates deletes all of the duplicates as well

### ISSUE THREAD

**Issue by goralight** [nukeop/nuclear#921] opened 2021-04-26 10:19 UTC
Steps:
1. Add a song to any playlist
2. Add the same song to the playlist
3. go to the playlist, and click delete on one of the items
4. notice how all duplicates are also deleted

Expected behavior:
It should only delete the single item you have selected to delete, regardless of duplicates.

**Comment by goralight** [comment] 2021-05-01 11:34
Has any work been done around this? If not I can pick it up if you like? @nukeop

**Comment by nukeop** [comment] 2021-05-01 21:01
Not yet. The problem is that playlists delete items by artist/title, not by unique id. I'll assign it to you then.

**Comment by nukeop** [comment] 2021-07-07 07:49
This should no longer occur

**Closed by nukeop** 2021-07-07 07:49 UTC
Labels: bug, good first issue
