### ISSUE TITLE
Arch Linux aur package nuclear-player-git broken

### ISSUE THREAD

**Issue by ghost** [nukeop/nuclear#1234] opened 2022-03-20 15:15 UTC
**Platform:**
Arch Linux 5.16.14-arch1-1
**Nuclear version:**
Aur - v0.6.11.r0.f1c09e7-1 (https://aur.archlinux.org/packages/nuclear-player-git)
**Description of the issue:**
Aur arch linux package "nuclear-player-git" is broken for me I don't know why but nuclear-player-bin package works for me. People are having the same problem. ( http://0x0.st/oNeQ.png , http://0x0.st/oNeS.png )
Here are all the logs - 
1) https://paste.rs/v8A  / https://0x0.st/oNe_.txt
2) Logs in  "/home/rounak/.npm/_logs/2022-03-20T15_07_11_502Z-debug-0.log" and "/home/rounak/.npm/_logs/2022-03-20T15_10_04_399Z-debug-0.log" Directory - https://0x0.st/oNej.txt , https://0x0.st/oNee.txt

**Comment by nukeop** [comment] 2022-03-20 21:03
Thanks for the detailed log - after reading it I think the cause is that you're using npm v8, it should work with v6. I'm working on upgrading dependencies currently, so that it works with the latest node and npm.

**Comment by nukeop** [comment] 2024-07-15 21:58
Fixed now.

**Closed by nukeop** 2024-07-15 21:58 UTC
Labels: bug
