### ISSUE TITLE
Windows 0.4.3 not playing

### ISSUE THREAD

**Issue by bbourdet** [nukeop/nuclear#122] opened 2019-01-16 16:05 UTC
Downloaded 0.4.3 and just did a search for bb king. Found a song, right clicked hit play this song. And now I am just looking at the nuclear logo, and nothing is happening.

**Comment by mikaelsouza** [comment] 2019-01-16 16:26
This is also happening in the macOS version.

**Comment by geckolinux** [comment] 2019-01-16 16:30
And also in the Linux version `nuclear-0.4.3-x86_64.AppImage`. I suspect it has something to do with the AppImage sandbox not communicating with PulseAudio.

**Comment by magalvao** [comment] 2019-01-16 17:15
Exactly same issue on Windows 8.1, version 0.4.3

**Comment by jajajaime** [comment] 2019-01-16 17:19
Same on macOS over here.

**Comment by peterloron** [comment] 2019-01-16 17:44
Same here. OSX 10.14.2

**Comment by nukeop** [comment] 2019-01-16 18:01
I think all of these are caused by an expired key baked into that build. Stay tuned for the next release, or download a development version. In the future, I'll think about better ways to distribute client keys.

**Comment by geckolinux** [comment] 2019-01-16 18:06
@nukeop Thanks for the reply. Are there AppImages of the development version anywhere?

**Comment by nukeop** [comment] 2019-01-16 18:11
Not right now, I'll try automating the releases later when I have time (this program is getting a lot of attention all of a sudden).

**Comment by saadshahd** [comment] 2019-01-16 20:46
@nukeop It happens after any Runtime Error even in the development using my own discog API tokens.

I will investigate more.

**Comment by geckolinux** [comment] 2019-02-06 15:52
Hi there, this still seems to be a problem with nuclear-0.4.4-x86_64.AppImage on openSUSE Tumbleweed. It loads playlists and the icon changes to playing state, but no sound.

**Comment by nukeop** [comment] 2019-02-06 16:22
I noticed that too, it's a different problem than the original one in this thread. It happens because apparently saved stream URLs are no longer valid after some time, and need to be regenerated.

**Comment by nukeop** [comment] 2019-03-18 22:52
Should be fixed now.

**Closed by nukeop** 2019-03-18 22:52 UTC
Labels: bug
