### ISSUE TITLE
Can't play any songs

### ISSUE THREAD

**Issue by menitoon** [nukeop/nuclear#1639] opened 2024-07-13 16:07 UTC
**Platform:**
-Window
**Nuclear version:**
-0.6.30
**Description of the issue:**
I simply can't get any songs to play, I tried changing the main plugin source(from youtube to soundcloud) but it didn't change anything and it still didn't work.

![image](https://github.com/user-attachments/assets/4daf89ef-bf05-47d8-9715-775ead423a72)
*Here is the screen I get when I attempt to play a song("Accordion" in this case)*

**Comment by nukeop** [comment] 2024-07-13 16:08
Duplicate of #1629, we're working on it.

**Closed by nukeop** 2024-07-13 16:08 UTC
Labels: bug
