### ISSUE TITLE
Icon not showing up in Ubuntu 21.10

### ISSUE THREAD

**Issue by tuxisawesome** [nukeop/nuclear#1217] opened 2022-02-28 13:48 UTC
I just installed nuclear using the system package installer and it does not show the icon. It shows a default gnome icon instead of the nuclear logo. I was using the latest deb package at the time.

**Platform:**
Dell latitude E7270 running Ubuntu 21.10; x86_64
**Nuclear version:**
2dd909
**Description of the issue:**
When I open up the system app tray, the nuclear is non-existent, and is replaced by a standard gnome "template" icon.

**Comment by nukeop** [comment] 2022-02-28 13:59
Duplicate of #374

**Closed by nukeop** 2022-02-28 13:59 UTC
Labels: bug
