### ISSUE TITLE
Full screen visualizer opacity

### ISSUE THREAD

**Issue by NicolasGuruphat** [nukeop/nuclear#1476] opened 2023-07-13 17:10 UTC
**Platform:**
Windows
**Nuclear version:**
v0.6.24
**Description of the issue:**
When the visualizer is in full screen, there is a grey effect over the image
![image](https://github.com/nukeop/nuclear/assets/82589938/18708fd4-0bd1-45a1-b6c5-7e99fef13ec6)

**Comment by nukeop** [comment] 2023-07-13 17:18
You're right that this is a bug, I've never considered this because when using the visualizer I just move the cursor to another monitor.

This needs to be fixed in the following way:
- Remove the hover css styles from the overlay element
- Instead, use setTimeout and add a mouse event listener that checks if the mouse has moved over this element. If it moved, set a timer for 3-5s, and apply the dark overlay
- When the timer expires, remove the overlay again
- Can probably be done using `useEffect`

**Comment by lalitkumawat1m** [comment] 2023-07-14 16:26
I want to work on this issue could you please assign it to me ?

**Comment by nukeop** [comment] 2023-07-14 20:10
Sure, please also check this: https://nukeop.gitbook.io/nuclear/contributing/contribution-guidelines

**Comment by lalitkumawat1m** [comment] 2023-07-15 15:39
Im facing issue in installing project my computer is showing that it is harmful for system

**ScreenShot**
<img width="960" alt="Screenshot 2023-07-15 205842" src="https://github.com/nukeop/nuclear/assets/91591901/d0976b38-82a9-4d2f-b04f-7c6ea3974fe6">

I have downloaded nuclear.Setup.0.6.24.exe file from https://github.com/nukeop/nuclear/releases
could you please tell me how to install it and what are the steps to reproduce this bug

**Comment by nukeop** [comment] 2023-07-15 16:15
Looks like a Windows problem

**Comment by NicolasGuruphat** [comment] 2023-07-17 07:57
Yes it is. You can force the installation by clicking more info

**Comment by NicolasGuruphat** [comment] 2023-07-19 14:51
Are you still working on this @lalitkumawat1m  ? I may try to fix it this weekend.

**Comment by lalitkumawat1m** [comment] 2023-07-19 15:17
> Are you still working on this @lalitkumawat1m  ? I may try to fix it this weekend. 

You can work on this issue

**Comment by Bhuminandan** [comment] 2023-08-13 12:23
@nukeop can you assign this to me?

**Comment by nukeop** [comment] 2023-08-13 12:25
No

**Comment by Bhuminandan** [comment] 2023-08-13 12:28
@nukeop Is someone already working on it?

**Comment by nukeop** [comment] 2023-08-13 12:32
No, but I don't see any Typescript code in your contributions, and I am no longer accepting contributions from random Github accounts.

**Comment by Bhuminandan** [comment] 2023-08-13 12:38
@nukeop Thank you for clarification. I must admit that I'm not familiar with TypeScript at the moment, I will try to find something related to js for now!

**Comment by pateldivyesh1323** [comment] 2023-08-15 13:08
Can you please assign this to me, I want to work on this?

**Comment by nukeop** [comment] 2023-08-15 18:19
Just as I said above, I don't see any Typescript code you've written.

**Comment by pateldivyesh1323** [comment] 2023-08-15 18:22
I just learnt typescript a month ago.

**Comment by nukeop** [comment] 2023-08-15 19:00
Can you show us any Typescript code you've written?

**Comment by pateldivyesh1323** [comment] 2023-08-15 19:16
https://github.com/pateldivyesh1323/react-typescript-project.git

**Comment by nukeop** [comment] 2023-08-15 19:30
Isn't this little more than a template? Anyway, you're free to fix this bug and open a PR, if you do I'll take a look. Check out the contribution guide in the docs. Remember to write tests and run the linter.

**Comment by pateldivyesh1323** [comment] 2023-08-15 19:38
ok👍🏻

**Comment by pateldivyesh1323** [comment] 2023-08-17 15:44
I am having problems setting up project locally.
![Screenshot (52)](https://github.com/nukeop/nuclear/assets/109150688/31d29bd9-a3cf-4a4f-bc12-8605188fc785)

**Comment by pateldivyesh1323** [comment] 2023-08-17 18:54
After running npm start i am getting this error.
![Screenshot (54)](https://github.com/nukeop/nuclear/assets/109150688/12fb0eeb-dd4f-488d-b2a9-b0a882644427)

**Comment by nukeop** [comment] 2023-08-17 19:05
Follow the process in the build pipelines, they're step by step instructions that have all the infromation you need to get it running. There's also a long development guide in the docs.

**Comment by pateldivyesh1323** [comment] 2023-08-18 15:46
I think there is a type problem in webpack.config.ts
![Screenshot (55)](https://github.com/nukeop/nuclear/assets/109150688/31a871ca-5aa6-4bdd-87ac-5abf9f54f688)
It got resolved by assigning type string[] to path.
![Screenshot (56)](https://github.com/nukeop/nuclear/assets/109150688/f1d1b6d4-765c-4d9f-a776-68a1c5607334)

**Comment by soumya-ranjan-pratap** [comment] 2023-10-02 08:27
Hello, @nukeop Can you please assign this issue to me I want to work on this. I assure that I will solve this.

**Comment by nukeop** [comment] 2023-10-02 08:31
I don't assign issues anymore. Just open a PR.

**Comment by GuillotJessica** [comment] 2023-11-27 17:45
How do I get permission to push a new branch and create a PR then @nukeop ?

**Comment by nukeop** [comment] 2023-11-27 21:08
Hiya, on Github you need to fork the repository first (top right). Then you get your own copy of the repo that you can push to, and after that you can open a pull request against my original repo.

**Comment by nukeop** [comment] 2024-03-03 15:20
Closed by #1563

**Closed by nukeop** 2024-03-03 15:20 UTC
Labels: bug, good first issue
