### ISSUE TITLE
Unable to access or use nuclear on macOS

### ISSUE THREAD

**Issue by kmatusze13** [nukeop/nuclear#349] opened 2019-06-08 20:38 UTC
Version of nuclear:
0.4.4

Operating system:
macOS Mojave 10.14.5

Reproducible steps that cause the issue:
1. Visit the official website, as seen in the README.md document
2. Click Get It Now button
3. Click on 0.4.4
4. Scroll down to Assets and click on nuclear-0.4.4-mac-zip
5. Wait for the download to start and right-click on the Nuclear icon
6. The following error message is displayed below:

What you expected to see, vs. what you actually saw: 
I expected to be able to use and see the nuclear software

Image, animations or link to video showing issue occurring:
See below

Code snippet demonstrating the issue: 
See below

![image](https://user-images.githubusercontent.com/40547864/59152121-7ee54380-8a03-11e9-933c-2175f7466b0e.png)

**Comment by nukeop** [comment] 2019-06-08 22:32
I'm not sure what's happened here but maybe it's just an unfinished or corrupted download. I know that many people were able to run it on Mac. Here it looks like it doesn't even load Electron. We'll need someone with a Mac to verify and chime in.

**Comment by leonlafa** [comment] 2019-06-18 13:29
I can confirm that downloading the nuclear app as a .zip file does run on the mac okay.

I can also provide a screen recording if necessary. 
<img width="1663" alt="Screenshot 2019-06-18 at 14 28 09" src="https://user-images.githubusercontent.com/44982724/59688312-54e70a80-91d5-11e9-8e54-59fc1a1991cd.png">

**Comment by nukeop** [comment] 2019-06-18 13:37
Good, so I guess we can close this.

**Closed by nukeop** 2019-06-18 13:37 UTC
Labels: bug, help wanted
