### ISSUE TITLE
AppImage does not work

### ISSUE THREAD

**Issue by atropy** [nukeop/nuclear#746] opened 2020-07-28 17:27 UTC
I cant seem to get the AppImage working. Haven't been able to install the web app using the snap release. I attach the error log here.

-------------------- ERROR LOG ------------------
      main › something fail during app bootstrap
      main › TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1931:112553)
    at t (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1931:111703)
    at Object../node_modules/abstract-socket/lib/abstract_socket.js (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1925:99612)
    at n (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1:211)
    at /tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1985:16185
    at e.exports (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1985:16778)
    at c (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1985:5395)
    at Object.e.exports.sessionBus (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:1985:5597)
    at lt.p.init (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:2187:46373)
    at new p (/tmp/.mount_nuclead1er5L/resources/app.asar/dist/main.js:2187:46190)
--------------------------------------------------------------

System Information
Ubuntu 16.04
Linux kernel 4.4.0.31

**Comment by kortewegdevries** [comment] 2020-08-02 09:17
Can you run the program by extracting the appimage and `chmod+x nuclear` and `./nuclear`?

**Comment by atdocboy** [comment] 2020-08-02 09:23
@kortewegdevries Thats exactly how I ran the appimage. 
I even tried using the .deb and the snap versions. They just dont seem to work.

I have even tried updating the nodejs and npm packages to their latest versions.

**Comment by kortewegdevries** [comment] 2020-08-02 10:27
Duplicate of this https://github.com/nukeop/nuclear/issues/611#issuecomment-583756423 Can't reproduce with deb or appimage on Ubuntu 20.04.

**Comment by fabianski7** [comment] 2020-10-03 17:11
See https://github.com/gatsbyjs/gatsby/issues/24559

**Comment by fabianski7** [comment] 2020-10-03 17:12
I was having the same problem, but after installing the `libvips` I could start the nuclear. But now I get this:

```
Gtk-Message: 14:08:03.476: Failed to load module "appmenu-gtk-module"
      main › (node:35689) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
      main › renderer › Cannot read property 'name' of undefined
      main › renderer › Cannot read property 'name' of undefined
      main › renderer › Cannot read property 'name' of undefined
      main › renderer › Cannot read property 'name' of undefined
      main › renderer › Cannot read property 'name' of undefined
      main › renderer › Cannot read property 'name' of undefined
```

**Comment by nukeop** [comment] 2020-10-21 21:57
I changed the problematic dependencies, can you try the new release? https://github.com/nukeop/nuclear/releases/tag/v0.6.6

**Comment by fabianski7** [comment] 2020-10-26 13:11
> I changed the problematic dependencies, can you try the new release? https://github.com/nukeop/nuclear/releases/tag/v0.6.6

yes, it's working fine now

**Comment by nukeop** [comment] 2020-10-26 15:18
Great, thanks

**Comment by chaosmonk1** [comment] 2021-04-07 18:44
Similar errror with 0.6.11 on Debian 11.

```
      main › (node:2357) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
      main › Something failed during app bootstrap
      main › TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/opt/nuclear/resources/app.asar/dist/main.js:2256:115456)
    at t (/opt/nuclear/resources/app.asar/dist/main.js:2256:114606)
    at Object../node_modules/abstract-socket/lib/abstract_socket.js (/opt/nuclear/resources/app.asar/dist/main.js:2250:309396)
    at r (/opt/nuclear/resources/app.asar/dist/main.js:1:118)
    at /opt/nuclear/resources/app.asar/dist/main.js:2310:16707
    at e.exports (/opt/nuclear/resources/app.asar/dist/main.js:2310:17300)
    at c (/opt/nuclear/resources/app.asar/dist/main.js:2310:5923)
    at Object.e.exports.sessionBus (/opt/nuclear/resources/app.asar/dist/main.js:2310:6125)
    at fr.p.init (/opt/nuclear/resources/app.asar/dist/main.js:2717:44369)
    at new p (/opt/nuclear/resources/app.asar/dist/main.js:2717:44188)
    at new fr (/opt/nuclear/resources/app.asar/dist/main.js:2849:420279)
    at Object.t.resolveInstance (/opt/nuclear/resources/app.asar/dist/main.js:2679:35651)
    at /opt/nuclear/resources/app.asar/dist/main.js:2679:37852
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/opt/nuclear/resources/app.asar/dist/main.js:2679:35421)
    at /opt/nuclear/resources/app.asar/dist/main.js:2679:37852
```

I would really love a working release of this project.  The last version that didn't immediately crash on startup for me was 0.5.1 back in 2019.

**Comment by nukeop** [comment] 2021-04-07 22:18
Can you try deleting `~/.config/Electron/config.json`?

**Comment by XutaxKamay** [comment] 2021-04-07 22:55
I've tried this ^ and got the same issue. I suppose this is because it uses my current electron's system installed instead the one inside the AppImage?

**Comment by chaosmonk1** [comment] 2021-04-08 02:37
> Can you try deleting ~/.config/Electron/config.json?

That file doesn't exist.

**Comment by nukeop** [comment] 2021-04-08 23:51
Debugging this now

**Comment by nukeop** [comment] 2021-04-09 00:00
90% sure this happens when dbus daemon is not running.

**Comment by XutaxKamay** [comment] 2021-04-09 02:10
dbus daemon seems to be running fine, so I don't think it's the problem, I'm also using Gentoo.

I'm getting something different now after I've tried to look a bit on it,

![image](https://user-images.githubusercontent.com/20893801/114118506-35106180-98e9-11eb-8d9a-ca03cf6368e4.png)

This is normal that it creates files under root and not under the user itself? I would expect it to create files as the user instead of root right?

**Comment by nukeop** [comment] 2021-04-09 07:26
Since this seems to be happening mainly on Gentoo, I'll try reproducing it on a VM. I think this might be a bug within the library we're using to handle mpris.

**Comment by chaosmonk1** [comment] 2021-04-09 23:42
> Since this seems to be happening mainly on Gentoo,

It happens on Debian 11 too.

**Comment by nukeop** [comment] 2021-04-10 00:47
@XutaxKamay Could you try this branch and tell me if this problem is fixed? https://github.com/nukeop/nuclear/tree/fix/746

**Comment by XutaxKamay** [comment] 2021-04-10 00:49
> @XutaxKamay Could you try this branch and tell me if this problem is fixed? https://github.com/nukeop/nuclear/tree/fix/746

Sure,

npm install & npm start?

**Comment by nukeop** [comment] 2021-04-10 01:18
`abs.connect` is from AbstractSocket, as seen here: https://github.com/saghul/node-abstractsocket/blob/b2c915ffb80ebfcc39fe9b87e92305523568b935/README.md

For now, I'm just logging errors and carrying on the init if any service fails to initialize. This allows the program to continue with degraded functionality. I was told that this abstract socket library might not be bundled correctly, causing this problem.

**Comment by XutaxKamay** [comment] 2021-04-10 01:27
> `abs.connect` is from AbstractSocket, as seen here: https://github.com/saghul/node-abstractsocket/blob/b2c915ffb80ebfcc39fe9b87e92305523568b935/README.md
> 
> For now, I'm just logging errors and carrying on the init if any service fails to initialize. This allows the program to continue with degraded functionality. I was told that this abstract socket library might not be bundled correctly, causing this problem.

Oh okay I see. Though the library doesn't seem very updated as well, but that might be not an issue.
And yeah it's okay, thank you for taking time to fix it.

**Closed** 2021-05-11 00:08 UTC
Labels: bug

**Comment by chaosmonk1** [comment] 2021-05-11 18:12
If this is fixed now, can you please make a new release?

**Comment by nukeop** [comment] 2021-05-11 21:09
Sure, I'll make one in the coming days.

**Comment by C-Entropy** [comment] 2021-06-07 08:12
Similar errror with 0.6.13 on Gentoo.
```
./nuclear-0.6.13.AppImage
      main › (node:30672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
      main › Something failed during app bootstrap
      main › TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:7:365763)
    at t (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:7:364913)
    at Object.../../node_modules/abstract-socket/lib/abstract_socket.js (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:1:98823)
    at r (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:1:118)
    at /tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:61:42683
    at e.exports (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:61:43284)
    at d (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:61:31791)
    at Object.e.exports.sessionBus (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:61:31993)
    at ir.p.init (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:478:15614)
    at new p (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:478:15433)
    at new ir (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:2935:173712)
    at Object.t.resolveInstance (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:432:39989)
    at /tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:432:42226
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:432:39759)
    at /tmp/.mount_nucleabhjGu6/resources/app.asar/dist/main.js:432:42226
```
