### ISSUE TITLE
Taskbar Icon not rendering correctly/completely

### ISSUE THREAD

**Issue by BusterTheBusta** [nukeop/nuclear#1044] opened 2021-08-30 19:26 UTC
**Platform:** Windows 10 Ver. 2004 Build 19041.1165

**Nuclear version:** 0.6.16

**Description of the issue:** The Logo/Icon of Nuclear is not rendering properly in the taskbar, as only the top most slither of it is rendered, and the rest is blankspace. I've stumbled upon this Issue in previous versions and it doesn't depend on wether I've downloaded Nuclear through winget or directly from the [site/github.] 

A link to a screenshot
(https://i.imgur.com/ts9iMu2.png)

**Comment by nukeop** [comment] 2021-08-30 19:38
Thanks for reporting, we'll need someone with access to Windows to debug this.

**Comment by PriyanshX1902** [comment] 2021-09-08 08:00
@nukeop  can I take up this issue?

**Comment by nukeop** [comment] 2021-09-08 08:28
Sure, if you can test this on Windows it would be great.

**Comment by PriyanshX1902** [comment] 2021-09-08 09:11
![image](https://user-images.githubusercontent.com/72353221/132481084-cac6a022-f71f-4910-b829-97b45e3995ae.png)
It renders fine in the taskbar when I run the application on my Windows 10.

**Comment by nukeop** [comment] 2021-09-08 09:15
Ok, somebody who can reproduce this will need to take a look then.

**Comment by BusterTheBusta** [comment] 2021-09-08 12:53
If this helps any in relation to rendering, my gpu is a Zotac Geforce 970 and I have an I7-4770K. I presume it is not a problem directly related to Electron, since Discord displays fine, but I am a very novice coder if anything, so take that with a big grain of salt.

**Comment by Venryx** [comment] 2021-09-08 14:30
I get the same issue as the OP on Windows:
![](https://i.imgur.com/qytt0WX.png)

I'm using an old version though (0.6.6), so it's possible it was fixed since then?

Anyway, I'm too lazy to debug it right now, but responding here for reference.

**Comment by anan93636369** [comment] 2021-09-17 06:10
I got the same issue as the OP on windows![image](https://user-images.githubusercontent.com/90018625/133733048-3547f172-698a-426e-b586-d210ea7491b1.png)I'm using the 0.6.16 version with windows 21H1 19043.1237

**Comment by nukeop** [comment] 2021-09-30 11:59
Fixed by #1057, thank you @1lluzi0nzz et al

**Closed by nukeop** 2021-09-30 11:59 UTC
Labels: bug, good first issue, help needed - Windows
