### ISSUE TITLE
Rewrite: A big rewrite in Rust

### ISSUE THREAD

**Issue by meowsocute** [nukeop/nuclear#1652] opened 2024-07-21 14:50 UTC
Dear coders, I'm a big fan of optimized, memory safe apps. so I would think its necessary to rewrite the backend(the electron part) in rust using [Tauri](https://tauri.app/) framework.

I would prefer Tauri framework instead of Electron.
Consider checking out the benchmark: [https://www.levminer.com/blog/tauri-vs-electron](https://www.levminer.com/blog/tauri-vs-electron).
Checkout these: [https://aptabase.com/blog/why-chose-to-build-on-tauri-instead-electron](https://aptabase.com/blog/why-chose-to-build-on-tauri-instead-electron).

**Comment by nukeop** [comment] 2024-07-21 15:10
This is a duplicate of #1310

**Closed by nukeop** 2024-07-21 15:10 UTC
Labels: enhancement
