### ISSUE TITLE
nuclear-player-bin not launching and working in arch

### ISSUE THREAD

**Issue by prorounak2005** [nukeop/nuclear#1320] opened 2022-09-12 17:51 UTC
**Platform:**
Arch Linux x86_64
**Nuclear version:**
nuclear-player-bin 1662247798134:202293_9bf1a4ce1070f344d3a7a7195428aff0-2
**Description of the issue:**
Nuclear player is not launching when I try to launch it from menu. 

```
[rounak@archissexy 23:20 ~]$ nuclear
      main › (node:31750) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 23:20:52.014: Failed to load module "colorreload-gtk-module"
Gtk-Message: 23:20:52.014: Failed to load module "window-decorations-gtk-module"
[31750:0912/232053.821168:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
[rounak@archissexy 23:20 ~]$
```

**Comment by nukeop** [comment] 2022-09-12 18:00
Duplicate of #1297 and #1268.  Try running with `--no-sandbox`, and please reopen if it doesn't help.

**Closed by nukeop** 2022-09-12 18:00 UTC
Labels: bug
