### ISSUE TITLE
Custom themes support

### ISSUE THREAD

**Issue by dovatti** [nukeop/nuclear#1283] opened 2022-05-20 05:28 UTC
I don't know if this is possible right now. Would be cool to tweak UI with custom CSS or themes - ideally like in Visual Studio Code.
What do you think? I could work on it 😁

**Comment by nukeop** [comment] 2022-05-20 07:11
Hi, this is technically a duplicate of #1277 
As I wrote in that issue, that would require some additional effort as Semantic UI has poor theming support (requiring consumers to recompile scss) and it would be hard to implement, but should be possible. We have a defined palette that could theoretically be swapped at runtime.

If you're willing to implement this I would be very happy to merge it. You can find our contribution guidelines here: https://nukeop.gitbook.io/nuclear/contributing/contribution-guidelines

**Closed** 2022-05-20 07:32 UTC
Labels: enhancement
