### ISSUE TITLE
Max retries when loading any song.

### ISSUE THREAD

**Issue by l3dlinux** [nukeop/nuclear#1489] opened 2023-08-05 07:42 UTC
**Platform:**
Garuda Linux dragonized
**Nuclear version:**
v0.6.28
**Description of the issue:**
max retries exceeded with trying to play any song and yes it doesn't matter what  I search all the same thing.

![Screenshot_4](https://github.com/nukeop/nuclear/assets/17328683/bfa153ff-edba-417c-9cf2-8c785bbf35fe)

**Comment by nukeop** [comment] 2023-08-05 09:55
Duplicate of #1488

**Closed by nukeop** 2023-08-05 09:55 UTC
Labels: bug
