### ISSUE TITLE
Doesn't close entirely

### ISSUE THREAD

**Issue by tiotrom** [nukeop/nuclear#682] opened 2020-04-03 23:10 UTC
Before you open a new issue, check this for solutions to some common problems:
https://nuclearmusic.readthedocs.io/en/latest/troubleshooting/
If you want to open a new issue anyway, delete this text.

When I close it from the X button, in Linux, it doesn't really close since I can see the process in System Monitor. And I cannot re-open it again unless I kill the process and then open Nuclear.
```
[tio@tio-pc ~]$ nuclear
      main › (node:930849) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  renderer › Error while searching  for Dua Lipa Physical on Youtube
  renderer › {}
  renderer › Error while searching  for Halsey Still Learning on Youtube
  renderer › {}
```
But this only happens from time to time so I thought to report it.

**Comment by nukeop** [comment] 2020-04-04 22:32
Hi, thanks for reporting. This is a duplicate of https://github.com/nukeop/nuclear/issues/668, so let's close this one and follow that one for updates on this issue.

**Closed by nukeop** 2020-04-04 22:32 UTC
Labels: bug
