### ISSUE TITLE
Uncaught exception: tried to write a message to a closed stream

### ISSUE THREAD

**Issue by ana-borges** [nukeop/nuclear#1081] opened 2021-10-22 19:02 UTC
**Platform:**

Linux/Debian testing (bookworm)

**Nuclear version:**

0.6.17

**Description of the issue:**

Before any song starts playing, this error appears. If I click ok, the song plays. Then after it ends I get the same error, and so on.

![image](https://user-images.githubusercontent.com/20948476/138508462-6f0a93ff-2076-41bd-a03e-8261eb420394.png)

**Comment by lfom** [comment] 2021-11-19 03:58
Same here on Pop!_OS 21.04 (like Ubuntu 21.04). It shows these three errors for each song, then usually the music starts playing.

![Screenshot from 2021-11-19 00-56-59](https://user-images.githubusercontent.com/15659999/142562507-da47f305-b8af-4338-b6e1-19c0e89f851f.png)

![Screenshot from 2021-11-19 00-57-02](https://user-images.githubusercontent.com/15659999/142562522-2f4991de-0748-45c3-af62-e79f0fb1fa4e.png)

![Screenshot from 2021-11-19 00-57-05](https://user-images.githubusercontent.com/15659999/142562535-d58abf3b-1ce4-43f9-ab4e-f62bf9b28a28.png)

**Comment by OatmanGeorge** [comment] 2021-11-19 19:38
Third this, on Mint but it won't even play, it  just crashes. Tried with both Appimage, and installing from repo.

**Comment by JaoPedroDev** [comment] 2021-11-23 17:58
Same here on Manjaro, happens whenever I try to play a music. Using [this one](https://aur.archlinux.org/packages/nuclear-player-bin/) from the AUR. If I click in "OK" multiples time, it disappear and the music play.

**Comment by Kleysley** [comment] 2021-11-24 19:48
This happens no matter what search source.

**Comment by nukeop** [comment] 2021-12-01 00:31
I tracked it down to this line on linux: https://github.com/nukeop/nuclear/blob/master/packages/main/src/services/%40linux/system-api.ts#L185

It looks like some more defensive coding is needed around this part to ensure that these apis are accessible before writing, or it will crash.

**Comment by nukeop** [comment] 2021-12-06 17:16
I tried reproducing this on Linux and Mac, to no avail. I'll ask around for help in debugging this.

**Comment by lfom** [comment] 2021-12-06 18:22
@nukeop Weird, I got the same error here using v0.6.17 with either the AppImage or the tarball (for some reason, the AppImage does not play the song after the errors while the tarball does) while using Garuda/Arch. These are the messages I got while running the AppImage from the terminal (same errors from the tarball, just different directories, of course):

```
$ ./nuclear-v0.6.17.AppImage 
      main › (node:77993) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
      main › (node:77993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:13798)
    at /tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:2154
    at new Promise (<anonymous>)
    at e.exports.request (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:2107)
    at e.exports.clearActivity (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:6785)
    at fr.clear (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:510734)
    at ca.onClearTrackList (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:531161)
    at IpcMainImpl.<anonymous> (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:536446)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:77993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:77993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      main › (node:77993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:13798)
    at /tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:2154
    at new Promise (<anonymous>)
    at e.exports.request (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:2107)
    at e.exports.clearActivity (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2200:6785)
    at fr.clear (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:510734)
    at App.<anonymous> (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:537783)
    at App.emit (events.js:327:22)
    at Lt.close (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:486639)
    at ha.onClose (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:533655)
    at IpcMainImpl.<anonymous> (/tmp/.mount_nucleax25HYw/resources/app.asar/dist/main.js:2751:536446)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:77993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

**Comment by Coderdude112** [comment] 2021-12-06 19:46
@nukeop I'm getting this error on the latest version v0.6.17 via the AUR.

**Comment by nukeop** [comment] 2021-12-06 22:21
Thanks for helping out, this clearly points to some incorrect handling of the mpris metadata.

**Comment by mkulik05** [comment] 2021-12-16 17:47
I have the same problem, when I try to play music in explore mode, 3 errors appears, after I skip them, music didn't start. But I can play music from the local library. Errors appears(in the start, end, when I add music to queue), I skip them and music starts playing. 

I installed nuclear-player-bin 0.6.17-2 from AUR

**Comment by system69-e** [comment] 2021-12-17 08:55
same problem here on manjaro

**Comment by maximmasterr** [comment] 2021-12-17 16:45
I tracked down to this [line](https://github.com/nukeop/nuclear/blob/e62f8ae7c7caa0beb868c6392dd8d2bcb088bbf2/packages/main/src/services/%40linux/system-api.ts#L51)

After some tests i found that, if there are dots in name parameter then application crashes. Possible fix is to hardcode 'netron' as name

**Comment by Noah-It-All** [comment] 2021-12-18 18:37
Same problem here, tested on latest manjaro and latest kali

**Comment by BobIsMyManager** [comment] 2021-12-27 19:16
On openSUSE tumbleweed i also get this issue on v0.6.17, but downgrading to v0.6.16 seems to make the issue no longer occur.

**Comment by nukeop** [comment] 2021-12-28 23:52
> I tracked down to this [line](https://github.com/nukeop/nuclear/blob/e62f8ae7c7caa0beb868c6392dd8d2bcb088bbf2/packages/main/src/services/%40linux/system-api.ts#L51)
> 
> After some tests i found that, if there are dots in name parameter then application crashes. Possible fix is to hardcode 'netron' as name

It's non-compliant with the MPRIS bus name policy: https://specifications.freedesktop.org/mpris-spec/latest/#Bus-Name-Policy

I found out that the current name is non-compliant either, I'll change it to comply.

**Comment by nukeop** [comment] 2021-12-28 23:57
I tracked it down, and `mpris-service` adds the app name to `org.mpris.MediaPlayer2.`, so the resulting name is wrong.

https://github.com/dbusjs/mpris-service/blob/81665c48ec8912aee210407e60d4b3bc114894b3/src/index.js#L180


I made a change on master that should resolve this problem; not sure if it will solve this issue altogether though. Can anyone verify if it works on master?

**Comment by lfom** [comment] 2021-12-29 02:46
@nukeop I tried, but building fails (Arch, `nvm use 12`, followed [dev process guide](https://nukeop.gitbook.io/nuclear/developer-resources/development-process)). I tried to install `lerna` globally, no go. [Logs](https://zerobin.net/?2da2582cb6a91a12#Bv9vvkzLl9cVEX8Sn1M43eHTy6mG5emjvZEObY+HzrE=).

**Comment by yaoberh** [comment] 2021-12-30 14:49
Getting the same error building from master in Manjaro.

**Comment by UltraBlackLinux** [comment] 2022-01-03 20:23
Same error here on Arch

**Comment by pedro-git-projects** [comment] 2022-01-12 23:40
Experiencing the same error on Arch Linux x86_64. 
![image](https://user-images.githubusercontent.com/73723028/149240255-4b839e71-5917-49ff-97af-48c32c347d44.png)

**Comment by nukeop** [comment] 2022-01-19 13:14
Looks like this is finally fixed on master.

**Closed by nukeop** 2022-01-19 13:14 UTC
Labels: bug

**Comment by lfom** [comment] 2022-01-19 20:21
@nukeop Nice! Any chances of a newer build so Linux uses can enjoy the app (since building it from sources does not seem to be trivial)? Thanks

**Comment by nukeop** [comment] 2022-01-19 20:28
I've built the binaries but a few things are in the middle of changes on master s they're unstable - I need to iron that out and I can build unversioned binaries. Building locally should be a matter of following the steps that github actions follow (clone, install dependencies, run the build), but I understand it's hard to debug if it fails.

Here are the binaries I built earlier: https://github.com/nukeop/nuclear/actions/runs/1715371299
Album pages are still broken because I need to add some tests and finish refactoring the track list.

**Comment by lfom** [comment] 2022-01-20 02:50
@nukeop Thank you for the link with the build. Indeed, the error is gone here using the AppImage.

Starting it from the terminal shows some warnings, I do not know if it is important:
```
$ Downloads/nuclear.AppImage
      main › (node:25367) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
      main › (node:25367) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/tmp/.mount_nucleakSgiuL/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /tmp/.mount_nucleakSgiuL/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/client.js:166:22
    at new Promise (<anonymous>)
    at e.exports.request (/tmp/.mount_nucleakSgiuL/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/client.js:164:12)
    at e.exports.clearActivity (/tmp/.mount_nucleakSgiuL/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/client.js:550:17)
    at fn.clear (/tmp/.mount_nucleakSgiuL/resources/app.asar/dist/webpack:/src/services/discord/index.ts:97:16)
    at da.name [as onClearTrackList] (/tmp/.mount_nucleakSgiuL/resources/app.asar/dist/webpack:/src/controllers/player.ts:63:18)
    at IpcMainImpl.<anonymous> (/tmp/.mount_nucleakSgiuL/resources/app.asar/dist/webpack:/src/utils/container.ts:54:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:25367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:25367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      main › error trying to set discord activity
```
And here on Gnome 41.3, two media controllers are shown while the music is playing.

![Screenshot from 2022-01-19 23-46-23](https://user-images.githubusercontent.com/15659999/150263346-a59c78ba-438f-4dcc-ab9f-3f828455e1b8.png)

**Comment by dolphinxyz** [comment] 2022-01-29 11:47
Hi Guys, I still have this issue.

I am running the latest release available.

Is there a way to run the app directly from git clone?

Thanks a ton

**Comment by yaoberh** [comment] 2022-01-29 12:58
Yep! Same issue here still too.

**Comment by nukeop** [comment] 2022-01-29 12:59
You need to build it yourself from master, or wait for the next release.

**Comment by Bacaliu** [comment] 2022-01-29 20:18
I've invented a ridiculous but effective Workaround for users of the i3 window manager. Just put the following in i3's config:

`for_window [class="Nuclear" title="Error"] kill`

**Comment by UltraBlackLinux** [comment] 2022-02-09 14:57
I just updated to 0.6.17 and the issue is back

**Comment by BobIsMyManager** [comment] 2022-02-09 16:22
This issue is fixed on the master branch/nightly builds, not 0.6.17
